# frozen_string_literal: true

require "pathname"
require "yaml"

require_relative "errors"

module NotionPublish
  # Where each document was published, and enough about it to tell whether
  # republishing has anything to do.
  #
  # Tool-written, never hand-edited, committed alongside the documents. One per
  # repository so that links between documents in different directories can be
  # resolved from a single place.
  class PageMap
    FILENAME = "notion-pages.yml"
    LEGACY_FILENAME = ".notion-publish.yml"

    HEADER = <<~TEXT
      # Generated by notion-publish. Do not edit by hand.
      # Maps each Markdown source to the Notion page it mirrors.
      # To re-point an entry, delete it and publish again.
      # Settings belong in .notion-publish.yml, which this tool never rewrites.
    TEXT

    ENTRY_FIELDS = %w[id url parent properties flag_properties title_override keep_h1 source_sha256
                      properties_sha256 flag_properties_sha256 notion_sha256 published_at].freeze

    # One published document.
    #
    # +flag_properties+ names the properties whose values came from
    # --property or --properties-json rather than front matter. Their values
    # are not recorded, so `republish` leaves them alone. It is nil on entries
    # written before it existed, which is how `republish` recognises them.
    # +title_override+ and +keep_h1+ record --title and --keep-h1 for the
    # same reason.
    Entry = Data.define(:id, :url, :parent, :properties, :flag_properties, :title_override, :keep_h1,
                        :source_sha256, :properties_sha256, :flag_properties_sha256,
                        :notion_sha256, :published_at) do
      # Only the page itself is required. Everything else accumulates: adopting
      # records no source hash, and older entries predate later fields.
      def initialize(id:, url:, parent: nil, properties: [], flag_properties: nil, title_override: nil,
                     keep_h1: nil, source_sha256: nil, properties_sha256: nil, flag_properties_sha256: nil,
                     notion_sha256: nil, published_at: nil)
        super
      end

      def to_h
        ENTRY_FIELDS.to_h { |field| [field, public_send(field)] }.compact
      end

      def self.from(hash)
        new(**ENTRY_FIELDS.to_h { |field| [field.to_sym, hash[field]] }, properties: hash["properties"] || [])
      end
    end

    attr_reader :path

    # --pages-file wins; then an existing file walking up; then a legacy
    # combined file to migrate; then the repository root; then the document's
    # own directory.
    def self.locate(document_path, override: nil, reporter: nil)
      locate_in(File.dirname(File.expand_path(document_path)), override: override, reporter: reporter)
    end

    # The same search, starting from a directory rather than a document.
    def self.locate_in(dir, override: nil, reporter: nil)
      return new(File.expand_path(override)) if override

      found = walk_up(dir) { |d| File.file?(File.join(d, FILENAME)) }
      return new(File.join(found, FILENAME)) if found

      legacy = walk_up(dir) { |d| legacy_state?(File.join(d, LEGACY_FILENAME)) }
      return migrate(File.join(legacy, LEGACY_FILENAME), reporter) if legacy

      root = walk_up(dir) { |d| File.directory?(File.join(d, ".git")) }
      new(File.join(root || dir, FILENAME))
    end

    def self.legacy_state?(path)
      return false unless File.file?(path)

      data = YAML.safe_load_file(path, permitted_classes: [], aliases: false)
      data.is_a?(Hash) && (data.key?("pages") || data.key?("databases"))
    rescue Psych::Exception
      false
    end

    # Earlier versions kept settings and state in one .notion-publish.yml. Move
    # the state across in place, so the keys -- which are relative to that
    # directory -- keep pointing at the same documents.
    def self.migrate(legacy_path, reporter)
      legacy = YAML.safe_load_file(legacy_path, permitted_classes: [], aliases: false) || {}
      map = new(File.join(File.dirname(legacy_path), FILENAME))
      map.pages.merge!(legacy["pages"] || {})
      map.databases.merge!(legacy["databases"] || {})
      map.save

      leftover = legacy.keys - %w[pages databases]
      reporter&.call(migration_message(legacy_path, map.path, leftover))
      map
    end

    def self.migration_message(legacy_path, new_path, leftover)
      lines = ["Moved published-page records out of #{legacy_path}", "into #{new_path}."]
      lines << if leftover.empty?
                 "#{File.basename(legacy_path)} now holds nothing; you can delete it."
               else
                 "Remove the pages/databases keys from #{File.basename(legacy_path)}; " \
                   "its settings (#{leftover.join(', ')}) are still read."
               end
      lines.join("\n")
    end

    def self.walk_up(dir)
      loop do
        return dir if yield(dir)

        parent = File.dirname(dir)
        return nil if parent == dir

        dir = parent
      end
    end

    def initialize(path)
      @path = path
      @data = File.file?(path) ? load_file : {}
      @created = !File.file?(path)
      # Keys removed in memory, so the merge with disk does not put them back.
      @forgotten = []
    end

    def dir = File.dirname(path)
    def created? = @created
    def pages = @data["pages"] ||= {}
    def databases = @data["databases"] ||= {}
    def workspace_id = @data["workspace_id"]

    def workspace_id=(value)
      @data["workspace_id"] = value if value && @data["workspace_id"] != value
    end

    def key_for(absolute_path)
      Pathname.new(File.expand_path(absolute_path)).relative_path_from(Pathname.new(dir)).to_s
    rescue ArgumentError
      File.expand_path(absolute_path)
    end

    def entry(absolute_path)
      raw = pages[key_for(absolute_path)]
      raw && Entry.from(raw)
    end

    def url_for(absolute_path) = entry(absolute_path)&.url

    def record(absolute_path, entry)
      pages[key_for(absolute_path)] = entry.to_h
      save
    end

    def forget(absolute_path)
      key = key_for(absolute_path)
      pages.delete(key)
      @forgotten << key
      save
    end

    # Entries whose source file no longer exists. Reported, never acted on: the
    # tool cannot tell a retirement from a rename.
    def orphans
      pages.keys.reject { |key| File.file?(File.expand_path(key, dir)) }
    end

    def writable?
      return File.writable?(path) if File.exist?(path)

      File.directory?(dir) && File.writable?(dir)
    end

    # Read-modify-write under an exclusive lock, so parallel invocations across a
    # corpus cannot drop each other's entries.
    def save
      raise Error, unwritable_message unless writable?

      # Lock the map itself rather than a sidecar: a stray .lock file next to
      # committed state is litter, and one more thing to gitignore.
      File.open(path, File::RDWR | File::CREAT, 0o644) do |file|
        file.flock(File::LOCK_EX)
        merged = merge_with_disk
        file.rewind
        file.truncate(0)
        file.write(HEADER + YAML.dump(sorted(merged)))
        @data = merged
      end
      @created = false
    end

    private

    def merge_with_disk
      on_disk = File.file?(path) ? load_file : {}
      merged = on_disk.merge(@data)
      merged["pages"] = (on_disk["pages"] || {}).merge(@data["pages"] || {})
      @forgotten.each { |key| merged["pages"].delete(key) }
      merged["databases"] = (on_disk["databases"] || {}).merge(@data["databases"] || {})
      merged.compact
    end

    # Sorted keys keep a one-document publish to a one-entry diff.
    def sorted(data)
      out = {}
      out["workspace_id"] = data["workspace_id"] if data["workspace_id"]
      out["pages"] = data["pages"].sort.to_h if data["pages"] && !data["pages"].empty?
      out["databases"] = data["databases"].sort.to_h if data["databases"] && !data["databases"].empty?
      out
    end

    def load_file
      loaded = YAML.safe_load_file(path, permitted_classes: [], aliases: false)
      raise ConfigError, malformed_message("expected a YAML mapping") unless loaded.nil? || loaded.is_a?(Hash)

      loaded || {}
    rescue Psych::Exception => e
      raise ConfigError, malformed_message(e.message)
    end

    # Refuse rather than starting from an empty map, which would republish
    # everything as new and duplicate the lot.
    def malformed_message(detail)
      <<~MSG.strip
        #{path} could not be read: #{detail}

        Publishing has stopped.
        Starting from an empty map would duplicate every published document.
        Fix the file, or delete it and re-adopt the existing pages deliberately.
      MSG
    end

    def unwritable_message
      <<~MSG.strip
        Cannot write #{path}.

        Checked before publishing on purpose: creating pages and then failing to
        record them is the one failure that cannot be retried safely.
      MSG
    end
  end
end
