# frozen_string_literal: true

require "test_helper"

class PageMapTest < Minitest::Test
  def entry(url: "https://notion.so/A", **overrides)
    defaults = {
      id: "p1", url: url, parent: { "type" => "data_source_id", "id" => "ds1", "name" => "Docs" },
      properties: %w[Function], source_sha256: "aaa", notion_sha256: "bbb",
      published_at: "2026-09-02T03:11:00Z"
    }
    NotionPublish::PageMap::Entry.new(**defaults, **overrides)
  end

  def test_an_entry_round_trips_through_the_file
    with_map do |map, dir|
      map.record(File.join(dir, "a.md"), entry)

      reloaded = NotionPublish::PageMap.new(map.path).entry(File.join(dir, "a.md"))

      assert_equal "p1", reloaded.id
      assert_equal %w[Function], reloaded.properties
      assert_equal "aaa", reloaded.source_sha256
    end
  end

  # The header explains the file to someone who has never used the tool, and
  # carries no timestamp so publishing one document is a one-entry diff.
  def test_the_generated_header_is_written_and_has_no_date
    with_map do |map, dir|
      map.record(File.join(dir, "a.md"), entry)
      text = File.read(map.path)

      assert_includes text, "Generated by notion-publish. Do not edit by hand."
      assert_includes text, ".notion-publish.yml, which this tool never rewrites"
      refute_match(/# .*20\d\d-\d\d-\d\d/, text.lines.first(4).join)
    end
  end

  def test_keys_are_written_in_sorted_order
    with_map do |map, dir|
      %w[zebra.md alpha.md middle.md].each { |n| map.record(File.join(dir, n), entry) }

      assert_equal %w[alpha.md middle.md zebra.md], YAML.safe_load_file(map.path)["pages"].keys
    end
  end

  def test_keys_are_relative_to_the_map
    with_map do |map, dir|
      map.record(File.join(dir, "sub", "a.md"), entry)

      assert_equal ["sub/a.md"], map.pages.keys
    end
  end

  # Parallel invocations read-modify-write the same file; neither may drop the
  # other's entries.
  def test_a_concurrent_write_is_not_lost
    with_map do |map, dir|
      other = NotionPublish::PageMap.new(map.path)
      map.record(File.join(dir, "a.md"), entry)
      other.record(File.join(dir, "b.md"), entry)

      assert_equal %w[a.md b.md], YAML.safe_load_file(map.path)["pages"].keys.sort
    end
  end

  # Locking the map itself, not a sidecar: a stray .lock beside committed state
  # is litter and one more thing to gitignore.
  def test_writing_leaves_no_other_files_behind
    with_map do |map, dir|
      map.record(File.join(dir, "a.md"), entry)

      assert_equal [NotionPublish::PageMap::FILENAME], Dir.children(dir).sort
    end
  end

  def test_entries_without_a_source_file_are_reported_as_orphans
    with_map do |map, dir|
      File.write(File.join(dir, "here.md"), "x")
      map.record(File.join(dir, "here.md"), entry)
      map.record(File.join(dir, "gone.md"), entry)

      assert_equal ["gone.md"], map.orphans
    end
  end

  def test_forgetting_removes_an_entry
    with_map do |map, dir|
      map.record(File.join(dir, "a.md"), entry)
      map.forget(File.join(dir, "a.md"))

      assert_empty map.pages
    end
  end

  # Starting from an empty map would republish everything as new.
  def test_a_malformed_map_refuses_rather_than_starting_empty
    Dir.mktmpdir do |dir|
      path = File.join(dir, NotionPublish::PageMap::FILENAME)
      File.write(path, "pages: [unclosed\n")

      error = assert_raises(NotionPublish::ConfigError) { NotionPublish::PageMap.new(path) }

      assert_includes error.message, "could not be read"
      assert_includes error.message, "would duplicate every published document"
    end
  end

  def test_an_unwritable_location_is_refused_before_publishing
    Dir.mktmpdir do |dir|
      readonly = File.join(dir, "ro")
      Dir.mkdir(readonly)
      File.chmod(0o500, readonly)
      map = NotionPublish::PageMap.new(File.join(readonly, NotionPublish::PageMap::FILENAME))

      error = assert_raises(NotionPublish::Error) { map.record(File.join(dir, "a.md"), entry) }

      assert_includes error.message, "Cannot write"
      assert_includes error.message, "cannot be retried safely"
    ensure
      File.chmod(0o700, readonly)
    end
  end

  # Earlier versions kept settings and state in one file. The state moves across
  # in place, so its keys keep pointing at the same documents.
  def test_a_legacy_combined_file_is_migrated_in_place
    Dir.mktmpdir do |dir|
      File.write(File.join(dir, NotionPublish::PageMap::LEGACY_FILENAME), <<~YAML)
        database: References
        pages:
          a.md:
            id: p1
            url: https://notion.so/A
        databases:
          References: ds1
      YAML

      said = []
      map = NotionPublish::PageMap.locate(File.join(dir, "a.md"), reporter: ->(m) { said << m })

      assert_equal File.join(dir, NotionPublish::PageMap::FILENAME), map.path
      assert_equal "p1", map.entry(File.join(dir, "a.md")).id
      assert_equal "ds1", map.databases["References"]
      assert_includes said.join, "Remove the pages/databases keys"
      assert_includes said.join, "database"
    end
  end

  def test_a_legacy_file_holding_only_state_is_reported_as_deletable
    Dir.mktmpdir do |dir|
      File.write(File.join(dir, NotionPublish::PageMap::LEGACY_FILENAME),
                 "pages:\n  a.md:\n    id: p1\n    url: https://notion.so/A\n")

      said = []
      NotionPublish::PageMap.locate(File.join(dir, "a.md"), reporter: ->(m) { said << m })

      assert_includes said.join, "you can delete it"
    end
  end

  def test_a_settings_only_file_is_not_mistaken_for_state
    Dir.mktmpdir do |dir|
      File.write(File.join(dir, NotionPublish::PageMap::LEGACY_FILENAME), "database: References\n")

      map = NotionPublish::PageMap.locate(File.join(dir, "a.md"))

      assert_predicate map, :created?, "nothing to migrate, so no map is written"
      refute_path_exists map.path
    end
  end

  # --pages-file wins; then an existing file; then the repo root; then here.
  def test_locate_prefers_an_explicit_path
    Dir.mktmpdir do |dir|
      chosen = File.join(dir, "elsewhere.yml")

      assert_equal chosen, NotionPublish::PageMap.locate(File.join(dir, "a.md"), override: chosen).path
    end
  end

  def test_locate_finds_an_existing_map_above_the_document
    Dir.mktmpdir do |dir|
      FileUtils.mkdir_p(File.join(dir, "deep", "deeper"))
      File.write(File.join(dir, NotionPublish::PageMap::FILENAME), "pages: {}\n")

      found = NotionPublish::PageMap.locate(File.join(dir, "deep", "deeper", "a.md"))

      assert_equal File.join(dir, NotionPublish::PageMap::FILENAME), found.path
    end
  end

  def test_locate_falls_back_to_the_repository_root
    Dir.mktmpdir do |dir|
      FileUtils.mkdir_p(File.join(dir, ".git"))
      FileUtils.mkdir_p(File.join(dir, "docs", "policies"))

      found = NotionPublish::PageMap.locate(File.join(dir, "docs", "policies", "a.md"))

      assert_equal File.join(dir, NotionPublish::PageMap::FILENAME), found.path
      assert_predicate found, :created?
    end
  end

  def test_locate_falls_back_to_the_documents_own_directory
    Dir.mktmpdir do |dir|
      found = NotionPublish::PageMap.locate(File.join(dir, "a.md"))

      assert_equal File.join(dir, NotionPublish::PageMap::FILENAME), found.path
    end
  end

  private

  def with_map
    Dir.mktmpdir do |dir|
      yield NotionPublish::PageMap.new(File.join(dir, NotionPublish::PageMap::FILENAME)), dir
    end
  end
end
